### ISSUE TITLE
Offset into offset and length

### ISSUE THREAD

**Issue by Mcrtin** [alexkazik/lzss#3]
I want to compress and decompress some files of an old game. The format uses a modified lzss algorithm: the offset starts at 0x3f0 and the length is offset by 3 (cuz 3 is the break even point) offset is 10 bit and length 4 bit. Can I use this lib regardless?

**Comment by alexkazik** [comment]
I don't know about the offset, that probably doesn't work. The encoded length is in this algorithm also reduced by the break even point (the `self.p() + 1` in https://github.com/alexkazik/lzss/blob/master/lzss/src/dynamic/compress.rs#L68).

Can you provide an example or code?

**Comment by Mcrtin** [comment]
```rust
fn decompress(cmp: &[u8]) -> Vec<u8> {
    let mut decmp = Vec::with_capacity(cmp.len() * 9 / 8);
    let mut mode = 0;

    let mut iter = cmp.iter();
    while let Some(&curr) = iter.next() {
        if mode & 0x100 == 0 {
            mode = (curr as u32) | 0xff00;
            continue;
        }
        if mode & 1 != 0 {
            decmp.push(curr);
        } else if let Some(&next) = iter.next() {
            let cp = (16 - decmp.len() + curr as usize + ((next & 0xf0) as usize) << 4)
                & 0x3ff + decmp.len() - 1024;

            for i in 0..(next & 0xf) as usize + 3 {
                decmp.push(decmp.get(cp + i).copied().unwrap_or(b' '));
            }
        }
        mode >>= 1;
    }
    decmp
}
```
you can see the 16 offset in cp and the 3 offset in the loop

**Comment by alexkazik** [comment]
Sorry, that will not work.

The algorithm I used uses a bitstream and stores something like:
"1" + 8bit plain data
"0" + x bit offset + y bit length
if the stream starts with a plain byte then it will be the "1" bit and the top 7 bits of the data in the first byte, and continues in the next byte.

Your algorithm stores interleaved bytes
first mode byte: 8 bits to tell for the next 8 "blocks" wether there are plain or copy
then 8 "blocks" of either the plain byte or two bytes (16bit) with offset+len

Which is even easier to implement but not as flexible - but either way is the encoded data different and it won't work.

Maybe I'll add this as a modified version at some point - it intrigues me but I have other projects for now.

**Comment by Mcrtin** [comment]
Unfortunate that it doesn't work out; regardless, thank you for the quick reply :D

**Comment by alexkazik** [comment]
You're welcome - and sorry.
